apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-rag-app
  labels:
    app: milvus-rag-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus-rag-app
  template:
    metadata:
      labels:
        app: milvus-rag-app
    spec:
      containers:
      - name: milvus-rag-app
        image: ghcr.io/aaronyang0628/milvus-rag-app:slim
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 30500
          name: http
        env:
        - name: HF_ENDPOINT
          value: https://hf-mirror.com
        - name: MILVUS_URI
          value: "https://in03-891eca6c21bd4e5.serverless.aws-eu-central-1.cloud.zilliz.com"
        - name: MILVUS_TOKEN
          value: "32dc6e16e03c11d52247a455ed827bb856077f1603b6b60b4d71f60b7a5f238b9ce73960ce9d4bda9aa9378a800bb9d8d521ec42"
        - name: TONGYI_API_KEY
          value: "sk-f0029ee74a454bddbe1a79c2d55aaca3"
        - name: QA_COLLECTION_NAME
          valueFrom:
            configMapKeyRef:
              name: milvus-rag-config
              key: QA_COLLECTION_NAME
        - name: EMBEDDING_MODEL
          valueFrom:
            configMapKeyRef:
              name: milvus-rag-config
              key: EMBEDDING_MODEL
        - name: EMBEDDING_DIM
          valueFrom:
            configMapKeyRef:
              name: milvus-rag-config
              key: EMBEDDING_DIM
        - name: LLM_MODEL
          valueFrom:
            configMapKeyRef:
              name: milvus-rag-config
              key: LLM_MODEL
        - name: GRABE_TOP_N_RES
          valueFrom:
            configMapKeyRef:
              name: milvus-rag-config
              key: GRABE_TOP_N_RES
        - name: EXT_DOC_PATH
          valueFrom:
            configMapKeyRef:
              name: milvus-rag-config
              key: EXT_DOC_PATH
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: milvus-rag-uploads-pvc