apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-rag-uploads-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "standard"